machine:
  node:
    version: 7.8.0
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/react-native-twilio-video-webrtc

dependencies:
  pre:
    - rm -rf ~/.yarn
    - npm i -g yarn
    - yarn -v
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn

jobs:
  test:
    steps:
      - checkout
      - *attach_workspace
      - run:
        name: Run tests
        command: yarn run ci
