# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'Example' do
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge'
  ]
  pod 'react-native-twilio-video-webrtc', path: '../../'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end
